CREATE TABLE `audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int,
	`userId` int,
	`userName` varchar(128),
	`action` varchar(64) NOT NULL,
	`tableName` varchar(64),
	`recordId` int,
	`oldValue` text,
	`newValue` text,
	`ipAddress` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` varchar(32) NOT NULL,
	`legalFirstName` varchar(128) NOT NULL,
	`legalLastName` varchar(128) NOT NULL,
	`preferredName` varchar(128),
	`dob` date,
	`phone` varchar(20),
	`email` varchar(320),
	`addressLine1` varchar(256),
	`city` varchar(128),
	`state` varchar(64),
	`zip` varchar(16),
	`ssnLast4` varchar(4),
	`roleAppliedFor` varchar(128),
	`serviceLine` enum('OLTL','ODP','Skilled'),
	`hiringSource` varchar(128),
	`submissionId` varchar(128),
	`submissionTimestamp` timestamp,
	`currentPhase` enum('Intake','Screening','Documentation','Verification','Provisioning','Ready to Schedule','Active','Post-Onboarding') DEFAULT 'Intake',
	`status` enum('Pending Review','In Progress','Action Required','On Hold','Complete','Withdrawn','Rejected') DEFAULT 'Pending Review',
	`nextAction` text,
	`owner` varchar(128),
	`dueDate` date,
	`priority` enum('High','Medium','Low') DEFAULT 'Medium',
	`escalationFlag` boolean DEFAULT false,
	`completionPercent` int DEFAULT 0,
	`dsPacket1EnvelopeId` varchar(128),
	`dsPacket1Status` enum('Not Sent','Sent','Delivered','Completed','Declined','Voided') DEFAULT 'Not Sent',
	`dsPacket1CompletedDate` date,
	`dsPacket2EnvelopeId` varchar(128),
	`dsPacket2Status` enum('Not Sent','Sent','Delivered','Completed','Declined','Voided') DEFAULT 'Not Sent',
	`dsPacket2CompletedDate` date,
	`i9Complete` boolean DEFAULT false,
	`i9VerifiedBy` varchar(128),
	`i9VerifiedDate` date,
	`patchReceived` boolean DEFAULT false,
	`patchDate` date,
	`fbiReceived` boolean DEFAULT false,
	`fbiDate` date,
	`childAbuseReceived` boolean DEFAULT false,
	`childAbuseDate` date,
	`physicalTbComplete` boolean DEFAULT false,
	`physicalTbDate` date,
	`cprComplete` boolean DEFAULT false,
	`cprExpDate` date,
	`licenseVerified` boolean DEFAULT false,
	`licenseNumber` varchar(64),
	`licenseExpDate` date,
	`payrollAdded` boolean DEFAULT false,
	`payrollVerifiedBy` varchar(128),
	`evvHhaProfileCreated` boolean DEFAULT false,
	`evvHhaProfileVerified` boolean DEFAULT false,
	`readyToSchedule` boolean DEFAULT false,
	`firstShiftDate` date,
	`firstShiftConfirmed` boolean DEFAULT false,
	`activeDate` date,
	`employeeFolderUrl` text,
	`offerFolderUrl` text,
	`applicationIntakeFolderUrl` text,
	`i9FolderUrl` text,
	`backgroundFolderUrl` text,
	`documentationFolderUrl` text,
	`medicalFolderUrl` text,
	`trainingFolderUrl` text,
	`payrollFolderUrl` text,
	`evvHhaFolderUrl` text,
	`hrNotes` text,
	`complianceNotes` text,
	`payRate` decimal(10,2),
	`payType` enum('Hourly','Salary'),
	`proposedStartDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	`lastModifiedBy` int,
	`googleSheetRowId` int,
	`lastSyncedAt` timestamp,
	CONSTRAINT `employees_id` PRIMARY KEY(`id`),
	CONSTRAINT `employees_employeeId_unique` UNIQUE(`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `exceptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`issue` text NOT NULL,
	`owner` varchar(128),
	`dueDate` date,
	`resolved` boolean DEFAULT false,
	`resolvedAt` timestamp,
	`resolvedBy` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exceptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gate_approvals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`gateType` enum('HR_COMPLETENESS_REVIEW','PAY_RATE_START_DATE_APPROVAL','CLEARANCES_VERIFICATION','I9_VERIFICATION','LICENSE_VERIFICATION','PAYROLL_VERIFICATION','EVV_HHA_VERIFICATION','SUPERVISOR_READY_SIGNOFF') NOT NULL,
	`status` enum('Pending','Approved','Rejected','Needs Review') DEFAULT 'Pending',
	`approvedBy` int,
	`approvedByName` varchar(128),
	`approvedAt` timestamp,
	`notes` text,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gate_approvals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `role_matrix` (
	`id` int AUTO_INCREMENT NOT NULL,
	`roleName` varchar(128) NOT NULL,
	`serviceLine` enum('OLTL','ODP','Skilled') NOT NULL,
	`requiredDocuments` text,
	`requiredClearances` text,
	`requiredTrainings` text,
	`skilledLicenseRequired` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `role_matrix_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sheets_sync` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spreadsheetId` varchar(256),
	`sheetName` varchar(128),
	`lastSyncAt` timestamp,
	`syncDirection` enum('to_sheets','from_sheets','bidirectional') DEFAULT 'bidirectional',
	`syncStatus` enum('idle','syncing','error','disabled') DEFAULT 'idle',
	`lastError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sheets_sync_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','hr','supervisor','compliance') NOT NULL DEFAULT 'user';