CREATE TABLE `employee_benefits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`benefitType` enum('Health Insurance','Dental Insurance','Vision Insurance','Life Insurance','401k','HSA','FSA','Other') NOT NULL,
	`planName` varchar(128),
	`planId` varchar(64),
	`coverageLevel` enum('Employee Only','Employee + Spouse','Employee + Children','Family'),
	`employeeContribution` decimal(10,2),
	`employerContribution` decimal(10,2),
	`contributionFrequency` enum('Per Pay Period','Monthly','Annual'),
	`enrollmentStatus` enum('Enrolled','Waived','Pending','Terminated') DEFAULT 'Pending',
	`effectiveDate` date,
	`terminationDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_benefits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employee_compensation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`employmentType` enum('Full-Time','Part-Time','PRN','Contract'),
	`flsaStatus` enum('Exempt','Non-Exempt') DEFAULT 'Non-Exempt',
	`payRate` decimal(10,2),
	`payType` enum('Hourly','Salary','Per Visit','Per Diem'),
	`payFrequency` enum('Weekly','Bi-Weekly','Semi-Monthly','Monthly'),
	`overtimeEligible` boolean DEFAULT true,
	`overtimeRate` decimal(5,2) DEFAULT '1.50',
	`weekendDifferential` decimal(10,2),
	`nightDifferential` decimal(10,2),
	`holidayRate` decimal(5,2),
	`annualSalary` decimal(12,2),
	`effectiveDate` date,
	`previousPayRate` decimal(10,2),
	`lastRaiseDate` date,
	`departmentCode` varchar(32),
	`costCenter` varchar(32),
	`jobCode` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_compensation_id` PRIMARY KEY(`id`),
	CONSTRAINT `employee_compensation_employeeId_unique` UNIQUE(`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `employee_direct_deposit` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`bankName` varchar(128),
	`accountType` enum('Checking','Savings'),
	`routingNumber` varchar(9),
	`accountNumber` varchar(17),
	`depositType` enum('Full','Percentage','Fixed Amount') DEFAULT 'Full',
	`depositAmount` decimal(10,2),
	`depositPercent` int,
	`priority` int DEFAULT 1,
	`isActive` boolean DEFAULT true,
	`isPrimary` boolean DEFAULT true,
	`voidedCheckReceived` boolean DEFAULT false,
	`verifiedBy` int,
	`verifiedDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_direct_deposit_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employee_tax_info` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`taxClassification` enum('W2','1099') DEFAULT 'W2',
	`ssnFull` varchar(11),
	`federalFilingStatus` enum('Single','Married Filing Jointly','Married Filing Separately','Head of Household'),
	`federalAllowances` int DEFAULT 0,
	`additionalFederalWithholding` decimal(10,2),
	`federalExempt` boolean DEFAULT false,
	`stateFilingStatus` varchar(64),
	`stateAllowances` int DEFAULT 0,
	`additionalStateWithholding` decimal(10,2),
	`stateExempt` boolean DEFAULT false,
	`workState` varchar(2),
	`residentState` varchar(2),
	`localTaxCode` varchar(32),
	`localWithholding` decimal(10,2),
	`multipleJobsOrSpouseWorks` boolean DEFAULT false,
	`dependentsAmount` decimal(10,2),
	`otherIncome` decimal(10,2),
	`deductions` decimal(10,2),
	`ein` varchar(12),
	`businessName` varchar(256),
	`w4ReceivedDate` date,
	`w4VerifiedBy` int,
	`w9ReceivedDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_tax_info_id` PRIMARY KEY(`id`),
	CONSTRAINT `employee_tax_info_employeeId_unique` UNIQUE(`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `hha_employee_mapping` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`hhaEmployeeId` varchar(64),
	`hhaProviderId` varchar(64),
	`lastSyncedAt` timestamp,
	`syncStatus` enum('synced','pending','error','not_synced') DEFAULT 'not_synced',
	`syncErrorMessage` text,
	`sourceSystem` enum('divine_touch','hha_exchange'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hha_employee_mapping_id` PRIMARY KEY(`id`),
	CONSTRAINT `hha_employee_mapping_employeeId_unique` UNIQUE(`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `payroll_exports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`exportType` enum('employee_new_hire','employee_update','payroll_run','hha_sync') NOT NULL,
	`targetSystem` enum('UKG','ADP','Paychex','HHA_Exchange','Generic_CSV') NOT NULL,
	`fileName` varchar(256),
	`fileUrl` text,
	`fileKey` varchar(256),
	`recordCount` int,
	`payPeriodId` int,
	`status` enum('pending','completed','failed','cancelled') DEFAULT 'pending',
	`errorMessage` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`exportedBy` int NOT NULL,
	`exportedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payroll_exports_id` PRIMARY KEY(`id`)
);
